title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://gowtham1997.github.io/website

aux_links:
  Template Repository: https://github.com/gowtham1997/CS639-website
