title: CS766 Project
description: CS766 Project Website
theme: just-the-docs

url: https://gowtham1997.github.io/website

aux_links:
  Template Repository: https://github.com/gowtham1997/CS766-website
