title: Benchmarking Efficient Transformers for Medical Image Classification - CS639 Project Website
description: CS639 Project Website
theme: just-the-docs

url: https://gowtham1997.github.io/website

aux_links:
  Template Repository: https://github.com/gowtham1997/CS639-website
